@startuml C4_Diabetes_Prediction_Form
!include https://raw.githubusercontent.com/plantuml-stdlib/C4-PlantUML/master/C4_Component.puml

class FormData {
    - Pregnancies: int
    - PlasmaGlucose: int
    - DiastolicBloodPressure: int
    - TricepsThickness: int
    - SerumInsulin: int
    - BMI: float
    - DiabetesPedigree: float
    - Age: int
}

Component(form, "Formulario HTML", "Formulario para ingresar datos de los usuarios") {
    
}

FormData --|> Object
form --|> FormData

@enduml
